
services:

  api:
    build: .
    container_name: realestate_api
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    container_name: realestate_ui
    ports:
      - "8501:8501"
    depends_on:
      - api